const genActionTypes = {
  ADD_LAYER: 'ADD_LAYER',
  REMOVE_LAYER: 'REMOVE_LAYER',
  ORDER_LAYERS: 'ORDER_LAYERS',
  ADD_IMAGE: 'ADD_IMAGE',
  UPDATE_IMAGE: 'UPDATE_IMAGE',
  REMOVE_IMAGE: 'REMOVE_IMAGE',
  ADD_PREVIEW: 'ADD_PREVIEW',
  REMOVE_PREVIEW: 'REMOVE_PREVIEW',
  UPDATE_PREVIEW: 'UPDATE_PREVIEW',
  SET_MINT_AMOUNT: 'SET_MINT_AMOUNT',
  SET_NFT_LAYERS: 'SET_NFT_LAYERS',
  SET_COMBINATIONS: 'SET_COMBINATIONS',
  SET_LOADING: 'SET_LOADING',
  SET_MINT_INFO: 'SET_MINT_INFO'
}

export default genActionTypes;