const genActionTypes = {
  ADD_LAYER: 'ADD_LAYER',
  REMOVE_LAYER: 'REMOVE_LAYER',
  UPDATE_LAYER: 'UPDATE_LAYER',
  ORDER_LAYERS: 'ORDER_LAYERS',
  ADD_IMAGE: 'ADD_IMAGE',
  UPDATE_IMAGE: 'UPDATE_IMAGE',
  REMOVE_IMAGE: 'REMOVE_IMAGE',
  ADD_PREVIEW: 'ADD_PREVIEW',
  REMOVE_PREVIEW: 'REMOVE_PREVIEW',
  UPDATE_PREVIEW: 'UPDATE_PREVIEW',
  SET_MINT_AMOUNT: 'SET_MINT_AMOUNT',
  SET_NFT_LAYERS: 'SET_NFT_LAYERS',
  SET_COMBINATIONS: 'SET_COMBINATIONS',
  SET_LOADING: 'SET_LOADING',
  SET_MINT_INFO: 'SET_MINT_INFO',
  DELETE_ASSET: 'DELETE_ASSET',
  SET_CURRENT_DNA_LAYERS: 'SET_CURRENT_DNA_LAYERS',
  RENAME_ASSET: 'RENAME_ASSET',
  SET_COLLECTION_NAME: 'SET_COLLECTION_NAME'
}

export default genActionTypes;